[package]
name = "brightdata_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true }
typed-builder = "0.18.2"
uuid = { version = "1.8.0", features = ["v4"] }

[workspace]
members = ["examples/*"]

[workspace.dependencies]
reqwest = "0.12.4"
