[package]
name = "simple"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
brightdata_proxy = { path = "../../." }
reqwest = { workspace = true }
tokio = { version = "1", features = ["full"] }
